### ISSUE TITLE
Support Cabal?

### ISSUE THREAD

**Issue by kindaro** [dfithian/prune-juice#1]
I do not think it works with Cabal. See:

    % mkdir x
    % cd x
    % cabal init

    Guessing dependencies...

    Generating LICENSE...
    Warning: unknown license type, you must put a copy in LICENSE yourself.
    Generating CHANGELOG.md...
    Generating app/Main.hs...
    Generating x.cabal...

    Warning: no synopsis given. You should edit the .cabal file and add one.
    You may want to edit the .cabal file and add a Description field.
    % prune-juice
    prune-juice: ./cabal.project: openBinaryFile: does not exist (No such file or directory)
    % edit cabal.project
    % prune-juice
    prune-juice: ./x.cabal: getDirectoryContents:openDirStream: inappropriate type (Not a directory)

So, it does not work on a basic Cabal package, even if I create a trivial `cabal.project` on top _(which is not required for a single package development)_. It also does not work on real projects I tried it with.

**Comment by dfithian** [comment]
Okay, I think at least using HEAD on the `main` branch should parse your cabal files... However I didn't do the work (yet) of fixing the call to `ghc-pkg`, so that will error out until someone takes it on.

**Comment by dfithian** [comment]
@kindaro Can you try off of HEAD now?

**Comment by kindaro** [comment]
It does not work when invoked on a new project the first time. Or rather, when there is no `dist-newstyle` in sight.

    % prune-juice
    Using build system cabal
    Using ignore list [base,hspec,tasty]
    ghc-pkg: /home/kindaro/.cabal/store/ghc-Resolving dependencies...
    8.10.4/package.db: getDirectoryContents:openDirStream: does not exist (No such file or directory)
    prune-juice: readCreateProcess: cabal "v2-exec" "ghc-pkg" "dump" "--" "--package-db" "/home/kindaro/.cabal/store/ghc-Resolving dependencies...\n8.10.4/package.db" (exit 1): failed
    % prune-juice
    Using build system cabal
    Using ignore list [base,hspec,tasty]
    % cabal clean
    % prune-juice
    Using build system cabal
    Using ignore list [base,hspec,tasty]
    ghc-pkg: /home/kindaro/.cabal/store/ghc-Resolving dependencies...
    8.10.4/package.db: getDirectoryContents:openDirStream: does not exist (No such file or directory)
    prune-juice: readCreateProcess: cabal "v2-exec" "ghc-pkg" "dump" "--" "--package-db" "/home/kindaro/.cabal/store/ghc-Resolving dependencies...\n8.10.4/package.db" (exit 1): failed

Other than that, it works.

**Comment by dfithian** [comment]
That's amusing. Okay, I think I fixed the parsing of the GHC version.

**Comment by kindaro** [comment]
Some more errors, this time after `cabal build`.

    % cabal clean
    % prune-juice
    Some unused base dependencies for package y
      aeson
    % cabal clean
    % prune-juice
    Some unused base dependencies for package y
      aeson
    % cabal clean
    % cabal build
    Resolving dependencies...
    Build profile: -w ghc-8.10.4 -O1
    In order, the following will be built (use -v for more details):
    - y-0.1.0.0 (exe:y) (first run)
    Configuring executable 'y' for y-0.1.0.0..
    Preprocessing executable 'y' for y-0.1.0.0..
    Building executable 'y' for y-0.1.0.0..
    [1 of 1] Compiling Main             ( app/Main.hs, /tmp/y/dist-newstyle/build/x86_64-linux/ghc-8.10.4/y-0.1.0.0/x/y/build/y/y-tmp/Main.o )
    Linking /tmp/y/dist-newstyle/build/x86_64-linux/ghc-8.10.4/y-0.1.0.0/x/y/build/y/y ...
    % prune-juice
    prune-juice: user error (Failed to parse name due to ParseErrorBundle {bundleErrors = TrivialError 0 (Just EndOfInput) (fromList [Tokens ('n' :| "ame:")]) :| [], bundlePosState = PosState {pstateInput = "", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}} original input )
    % prune-juice
    prune-juice: user error (Failed to parse name due to ParseErrorBundle {bundleErrors = TrivialError 0 (Just EndOfInput) (fromList [Tokens ('n' :| "ame:")]) :| [], bundlePosState = PosState {pstateInput = "", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}} original input )

I think it might be worthwhile to build a property check that takes a list of command tokens — an appropriate sum type — and executes the corresponding commands in order, collecting their exit status. For example, any list of commands `cabal build`, `cabal clean` and `prune-juice` should execute with every command returning status 0.

**Comment by dfithian** [comment]
Yeah. It's definitely a good idea. I don't have much experience with using Cabal directly so it's difficult to think through the error cases. Can you upload your cabal file(s)?

**Comment by kindaro** [comment]
There is really nothing to upload. I simply run `cabal init` in an empty directory, and maybe add some dependencies by hand such as the `aeson` dependency you may see in the log above.

**Comment by dfithian** [comment]
I see. I have added some tests. Trying to do quick iteration on this so that I can get something out there, so they're probably not the _best_ tests, but I did reproduce your latest error and believe I have fixed it.

**Comment by kindaro** [comment]
Yes, I cannot elicit any more errors! It works!

**Comment by dfithian** [comment]
Great! Please don't hesitate to file another issue if you run into something else.
