### ISSUE TITLE
`prune-juice --apply` will empty the cabal file if parsing failed

### ISSUE THREAD

**Issue by ksqsf** [dfithian/prune-juice#17]

**Comment by dfithian** [comment]
Can you please provide an example of the command you ran and your cabal file

**Comment by ksqsf** [comment]
ah so it's trickier than I thought. I just ran `prune-juice --apply` and it would report `Failed to parse cabal sections for ./ksqsf-services.cabal due to ParseErrorBundle`. I tried to trim the cabal file a bit but even very small changes (like removing `synopsis` line) would make it parse successfully.

my cabal file is [here](https://gist.github.com/ksqsf/2b4e6b09eb6548d39e8168b11a92efda), the repo of which unfortunately cannot be made public at the moment. Hope it helps.

**Comment by dfithian** [comment]
Aha! Good find. https://github.com/dfithian/prune-juice/pull/18. Please let me know if that fixes your issue.
