### ISSUE TITLE
[pip] Is there any way to apply the results to the project files?

### ISSUE THREAD

**Issue by mirko-plowtech** [dfithian/prune-juice#6]
I mean, it would be nice to provide a way to use the output (list of unneeded libraries) in order to automatically apply the changes (remove them from `build-depends` list) in the `.cabal` or `.stack` project files.

**Comment by mirko-plowtech** [comment]
pip: Prune-juice Improvement Proposal (?) hehe

**Comment by dfithian** [comment]
I agree! You’re not the first to suggest it. I’m thinking it would work by promoting the user to apply changes… however due to the caveats outlined in the readme I think the user would need to be able to select a subset of the packages presented. Does that make sense?

**Comment by mirko-plowtech** [comment]
> I agree! You’re not the first to suggest it. I’m thinking it would work by promoting the user to apply changes… however due to the caveats outlined in the readme I think the user would need to be able to select a subset of the packages presented. Does that make sense?


Select a subset would be ideal. But anyway, maybe a `--no-verify` flag that applies all suggested changes would be enough. I mean, IMHO, is less tedious to fix missing stuff than manually remove each lib. Worst case scenario, you build again, and check that everything still works, in case is broken, you manually fixed, but the optimistic flow it would be really helpful (for example with support for this feature, it would be possible to add this pruning as a pre-commit stage, and then CI will tell me if I fucked up things or not hehe)

**Comment by dfithian** [comment]
This one's a work in progress: https://github.com/dfithian/prune-juice/pull/12

There are more details in the description.

**Comment by dfithian** [comment]
Wow, I did not realize it took me over a month to even start on this. Sorry about that.

**Comment by mirko-plowtech** [comment]
> Wow, I did not realize it took me over a month to even start on this. Sorry about that.

np, It is awesome to see a PR addressing this =) thank you very much!
